name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Executa todos os dias à meia-noite
  workflow_dispatch: # Permite execução manual

# Impede execuções simultâneas no mesmo branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Define timeout para evitar consumo excessivo de minutos
    
    # Define permissões mínimas necessárias
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Pacman Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          output_action: commit
          committer_branch: output
          filename: pacman-contribution-graph.svg

